# DataSource (Spring Boot)
spring.datasource.url=jdbc:mysql://\
  ${MYSQLDB_HOST:localhost}:${MYSQLDB_PORT:3306}/${MYSQLDB_DATABASE:online_book_store}?\
  allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLDB_USER:root}
spring.datasource.password=${MYSQLDB_PASSWORD:Root123$}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.expiration=${JWT_EXPIRATION:300000}
jwt.secret=${JWT_SECRET:hellomateshellomateshellomateshellomates}
